spring:
  application:
    name: books-manage
  datasource:
    url: jdbc:mysql://localhost:3306/library?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true
server:
  port: 10010
logging:
  config: classpath:logback-spring.xml
  level:
    com:
      glmapper:
        spring:
          boot:
            level: INFO
